### ISSUE TITLE
Crash after pressure test when player leave.

### ISSUE THREAD

**Issue by anjisuan783** [anjisuan783/mia#39]
[WARN]2022-1-13 18:44:29,609[0x7f3a3a5fe700]SrsGopCache:cache:68>clear gop cache for guess pure audio overflow
[TRACE]2022-1-13 18:46:05,890[0x7f3a3a4fd700]WebRtcConnection:id: Knfs,  transportName: video, new_state: 5
[INFO]2022-1-13 18:46:05,891[0x7f3a3a4fd700]WebRtcConnection:id: Knfs,  newGlobalState: 500
[TRACE]2022-1-13 18:46:05,891[0x7f3a3a4fd700]wa.pc:Knfs, update status:500
[DEBUG]2022-1-13 18:46:05,891[0x7f3a3a4fd700]wa.pc:Knfs, CONN_FAILED, msg:id: Knfs,  message: Transport Failed, transportType:video, code:3
[INFO]2022-1-13 18:46:05,891[0x7f3a3a4fd700]MediaRtcAttendee:onFailed:288>pc[Knfs] disconnected
[TRACE]2022-1-13 18:46:05,891[0x7f3a3a4fd700]wa.pc:[unSubscribe:599](0x7f3a28038020)s:mXxd d:Knfs
[INFO]2022-1-13 18:46:05,891[0x7f3a3a4fd700]MediaRtcSource:OnAttendeeLeft:150>subscriber Knfs left
[INFO]2022-1-13 18:46:05,891[0x7f3a3a3fc700]wa.pc:video unsub, s:mXxd d:Knfs
[TRACE]2022-1-13 18:46:05,892[0x7f3a3a3fc700]wa.pc:[removeDestination:159](0x7f3a15861370)mXxd,v, dest:0x7f3a1c4ab7b0
[TRACE]2022-1-13 18:46:05,892[0x7f3a3a4fd700]wa.pc:[~WebrtcTrack:102](0x7f3a1de62f30)Knfs,WebrtcTrack dtor mid:1,video

#0  0x00007f3a3fd18387 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f3a3fd19a78 in __GI_abort () at abort.c:90
#2  0x000000000067cf05 in rtc::webrtc_checks_impl::FatalLog(char const*, int, char const*, rtc::webrtc_checks_impl::CheckArgType const*, ...) (file=file@entry=0xa8b1e8 "/home/mia-master/rtc_stack/owt/rtc_adapter/thread/ProcessThreadMock.cpp", line=line@entry=76, message=message@entry=0xa8b169 "thread_checker_.IsCurrent()", fmt=<optimized out>,
    fmt@entry=0xa7b6ec <void rtc::webrtc_checks_impl::LogStreamer<>::Call<>(char const*, int, char const*)::t>)
    at /home/mia-master/rtc_stack/myrtc/rtc_base/checks.cc:155
#3  0x00000000007057d8 in rtc_adapter::ProcessThreadMock::DeRegisterModule(webrtc::Module*) (message=0xa8b169 "thread_checker_.IsCurrent()", line=76, file=0xa8b1e8 "/home/mia-master/rtc_stack/owt/rtc_adapter/thread/ProcessThreadMock.cpp") at /home/mia-master/rtc_stack/myrtc/rtc_base/checks.h:222
#4  0x00000000007057d8 in rtc_adapter::ProcessThreadMock::DeRegisterModule(webrtc::Module*) (streamer=..., this=<optimized out>) at /home/mia-master/rtc_stack/myrtc/rtc_base/checks.h:294
#5  0x00000000007057d8 in rtc_adapter::ProcessThreadMock::DeRegisterModule(webrtc::Module*) (this=0x7f3a1de85030, module=0x7f3a1c9a3a00) at /home/mia-master/rtc_stack/owt/rtc_adapter/thread/ProcessThreadMock.cpp:76
#6  0x000000000065e4e8 in rtc_adapter::VideoSendAdapterImpl::~VideoSendAdapterImpl() (this=0x7f3a1de84f20, __in_chrg=<optimized out>) at /home/mia-master/rtc_stack/owt/rtc_adapter/VideoSendAdapter.cc:139
#7  0x000000000065e5c9 in rtc_adapter::VideoSendAdapterImpl::~VideoSendAdapterImpl() (this=0x7f3a1de84f20, __in_chrg=<optimized out>) at /home/mia-master/rtc_stack/owt/rtc_adapter/VideoSendAdapter.cc:141
#8  0x0000000000658c74 in owt_base::VideoFramePacketizer::~VideoFramePacketizer() (this=0x7f3a1c4ab7b0, __in_chrg=<optimized out>) at /home/mia-master/rtc_stack/owt/owt_base/VideoFramePacketizer.cpp:36
#9  0x000000000045cc96 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (this=0x7f3a1c4ab7a0)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr_base.h:154
#10 0x000000000060c3be in wa::WrtcAgentPc::<lambda(std::shared_ptr<wa::WrtcAgentPc>)>::operator()(std::shared_ptr<wa::WrtcAgentPc>) const (this=<optimized out>, __in_chrg=<optimized out>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr_base.h:684
#11 0x000000000060c3be in wa::WrtcAgentPc::<lambda(std::shared_ptr<wa::WrtcAgentPc>)>::operator()(std::shared_ptr<wa::WrtcAgentPc>) const (this=<optimized out>, __in_chrg=<optimized out>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr_base.h:1123
#12 0x000000000060c3be in wa::WrtcAgentPc::<lambda(std::shared_ptr<wa::WrtcAgentPc>)>::operator()(std::shared_ptr<wa::WrtcAgentPc>) const (__r=<unknown type in /home/mia-master/mia, CU 0xb049bf, DIE 0xba6507>, this=<synthetic pointer>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr_base.h:1213
#13 0x000000000060c3be in wa::WrtcAgentPc::<lambda(std::shared_ptr<wa::WrtcAgentPc>)>::operator()(std::shared_ptr<wa::WrtcAgentPc>) const (__r=<unknown type in /home/mia-master/mia, CU 0xb049bf, DIE 0xba64e1>, this=<synthetic pointer>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr.h:319
#14 0x000000000060c3be in wa::WrtcAgentPc::<lambda(std::shared_ptr<wa::WrtcAgentPc>)>::operator()(std::shared_ptr<wa::WrtcAgentPc>) const (__closure=0x7f3a1c03bcf0, this_pc=std::shared_ptr (count 3, weak 4) 0x7f3a28038020)
    at /home/mia-master/rtc_stack/wa/webrtc_agent_pc.cpp:638
#15 0x000000000060d0af in std::_Function_handler<void(std::shared_ptr<wa::WrtcAgentPc>), wa::WrtcAgentPc::subscribe_i(std::shared_ptr<wa::WrtcAgentPc>, bool)::<lambda(std::shared_ptr<wa::WrtcAgentPc>)> >::_M_invoke(const std::_Any_data &, <unknown type in /home/mia-master/mia, CU 0xb049bf, DIE 0xbb0d68>) (__functor=..., __args#0=<optimized out>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_function.h:316
#16 0x000000000060b61d in std::_Function_handler<void(), wa::WrtcAgentPc::asyncTask(std::function<void(std::shared_ptr<wa::WrtcAgentPc>)>)::<lambda()> >::_M_invoke(const std::_Any_data &) (__args#0=std::shared_ptr (count 26184864, weak -1) 0x7f3a3a3fbc60, this=<optimized out>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_function.h:706
#17 0x000000000060b61d in std::_Function_handler<void(), wa::WrtcAgentPc::asyncTask(std::function<void(std::shared_ptr<wa::WrtcAgentPc>)>)::<lambda()> >::_M_invoke(const std::_Any_data &) (__closure=<optimized out>)
    at /home/mia-master/rtc_stack/wa/webrtc_agent_pc.cpp:770
#18 0x000000000060b61d in std::_Function_handler<void(), wa::WrtcAgentPc::asyncTask(std::function<void(std::shared_ptr<wa::WrtcAgentPc>)>)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_function.h:316
#19 0x0000000000606b45 in webrtc::webrtc_new_closure_impl::ClosureTask<std::function<void ()>&>::Run() (this=<optimized out>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_function.h:706
#20 0x0000000000606b45 in webrtc::webrtc_new_closure_impl::ClosureTask<std::function<void ()>&>::Run() (this=<optimized out>) at /home/mia-master/rtc_stack/myrtc/rtc_base/to_queued_task.h:31
#21 0x00000000006a0155 in webrtc::(anonymous namespace)::TaskQueueLibevent::OnWakeup(int, short, void*) (socket=<optimized out>, flags=<optimized out>, context=<optimized out>)
    at /home/mia-master/rtc_stack/myrtc/rtc_base/task_queue_libevent.cc:280
#22 0x00000000007e493a in event_base_loop (base=<optimized out>)
    at /home/mia-master/rtc_stack/3rd/libevent/event.c:381
#23 0x00000000007e493a in event_base_loop (base=0x18f8660, flags=flags@entry=0)
    at /home/mia-master/rtc_stack/3rd/libevent/event.c:521
#24 0x000000000069f6eb in webrtc::(anonymous namespace)::TaskQueueLibevent::ThreadMain(void*) (context=0x18f73c0)
    at /home/mia-master/rtc_stack/myrtc/rtc_base/task_queue_libevent.cc:251
#25 0x00000000007347f9 in rtc::PlatformThread::StartThread(void*) (param=<optimized out>)
    at /home/mia-master/rtc_stack/myrtc/rtc_base/platform_thread.cc:67
#26 0x00007f3a417f0ea5 in start_thread (arg=0x7f3a3a3fc700) at pthread_create.c:307
#27 0x00007f3a3fde09fd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by anjisuan783** [comment]
Publisher and subscriber are in different thread.

**Comment by anjisuan783** [comment]
fixed
but join slow.
